package seedu.address.model.person;

import static java.util.Objects.requireNonNull;
import static seedu.address.commons.util.CollectionUtil.requireAllNonNull;

import java.util.Collections;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import java.util.function.Consumer;

import seedu.address.commons.util.ToStringBuilder;
import seedu.address.model.tag.AbstractTag;

/**
 * Represents a Teaching Staff member in the address book.
 * Extends Person with an additional position field and availability time slots.
 * Teaching staff have position "Teaching Assistant" by default.
 * Guarantees: details are present and not null, field values are validated, immutable.
 */
public non-sealed class TeachingStaff extends Person {

    /** Default position for teaching staff when not specified. */
    public static final String DEFAULT_POSITION_VALUE = Position.TEACHING_ASSISTANT;

    /** Prefix for generated staff phone numbers (8xxxxxxx). */
    private static final String DEFAULT_PHONE_PREFIX = "8";
    /** Number of digits in the generated part of default phone (7 digits, so 10^7 range). */
    private static final int DEFAULT_PHONE_MODULO = 10_000_000;
    /** Default email domain for staff when only name is provided. */
    private static final String DEFAULT_EMAIL_DOMAIN = "staff.local";
    /** Fallback local part when name yields no valid email local part. */
    private static final String DEFAULT_EMAIL_LOCAL_FALLBACK = "staff";
    /** Prefix for generated staff username. */
    private static final String DEFAULT_USERNAME_PREFIX = "staff";

    protected Position position;
    protected Set<TimeSlot> availability = new HashSet<>();
    private final boolean hasAutoGeneratedContactDetails;

    /**
     * Constructs teaching staff with name only; phone, email, username and position use defaults.
     * Position is set to {@value #DEFAULT_POSITION_VALUE}.
     *
     * @param name A valid name (required).
     */
    public TeachingStaff(Name name) {
        this(name, Collections.emptySet());
    }

    /**
     * Constructs teaching staff with name and tags; other fields use defaults.
     *
     * @param name A valid name (required).
     * @param tags Tags for the staff (can be empty).
     */
    public <T extends AbstractTag> TeachingStaff(Name name, Set<T> tags) {
        super(
                name,
                defaultPhoneForName(name, 0),
                defaultEmailForName(name, 0),
                defaultUsernameForName(name, 0),
                tags
        );
        this.hasAutoGeneratedContactDetails = true;
        this.position = new Position(DEFAULT_POSITION_VALUE);
    }

    /**
     * Every field must be present and not null.
     */
    public <T extends AbstractTag> TeachingStaff(Name name, Phone phone, Email email, Username username,
                         Position position, Set<T> tags) {
        super(name, phone, email, username, tags);
        requireAllNonNull(position);
        this.hasAutoGeneratedContactDetails = false;
        this.position = position;
    }

    /**
     * Full constructor including availability time slots.
     */
    public <T extends AbstractTag> TeachingStaff(Name name, Phone phone, Email email, Username username,
                         Position position, Set<T> tags, Set<TimeSlot> availability) {
        super(name, phone, email, username, tags);
        requireAllNonNull(position, availability);
        this.hasAutoGeneratedContactDetails = false;
        this.position = position;
        this.availability.addAll(availability);
    }

    private static Phone defaultPhoneForName(Name name, int offset) {
        int code = Math.floorMod(Math.abs(name.fullName.hashCode()) + offset, DEFAULT_PHONE_MODULO);
        return new Phone(String.format(DEFAULT_PHONE_PREFIX + "%07d", code));
    }

    private static Email defaultEmailForName(Name name, int suffix) {
        String local = name.fullName.replaceAll("\\s+", "").toLowerCase()
                .replaceAll("[^a-zA-Z0-9]", "");
        if (local.isEmpty()) {
            local = DEFAULT_EMAIL_LOCAL_FALLBACK;
        }
        if (suffix > 0) {
            local = local + suffix;
        }
        return new Email(local + "@" + DEFAULT_EMAIL_DOMAIN);
    }

    private static Username defaultUsernameForName(Name name, int suffix) {
        String base = name.fullName.replaceAll("\\s+", "");
        if (!Username.isValidUsername(base)) {
            base = DEFAULT_EMAIL_LOCAL_FALLBACK;
        }
        if (suffix > 0) {
            base = base + suffix;
        }
        return new Username(DEFAULT_USERNAME_PREFIX + base);
    }

    /**
     * Returns true if this teaching staff was created from the name-only add flow,
     * where phone/email/username were auto-generated.
     */
    public boolean hasAutoGeneratedContactDetails() {
        return hasAutoGeneratedContactDetails;
    }

    /**
     * Generates a default phone for the provided name with an offset to avoid collisions.
     */
    public static Phone generateDefaultPhone(Name name, int offset) {
        return defaultPhoneForName(name, offset);
    }

    /**
     * Generates a default email for the provided name with an optional positive suffix.
     */
    public static Email generateDefaultEmail(Name name, int suffix) {
        return defaultEmailForName(name, suffix);
    }

    /**
     * Generates a default username for the provided name with an optional positive suffix.
     */
    public static Username generateDefaultUsername(Name name, int suffix) {
        return defaultUsernameForName(name, suffix);
    }

    public Position getPosition() {
        return position;
    }

    /**
     * Returns an immutable set of availability time slots.
     */
    public Set<TimeSlot> getAvailability() {
        return Collections.unmodifiableSet(availability);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }

        if (!(other instanceof TeachingStaff)) {
            return false;
        }

        TeachingStaff otherStaff = (TeachingStaff) other;
        return super.equals(otherStaff)
                && position.equals(otherStaff.position)
                && availability.equals(otherStaff.availability);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, phone, email, username, position, tags, availability);
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .add("name", name)
                .add("phone", phone)
                .add("email", email)
                .add("username", username)
                .add("position", position)
                .add("tags", tags)
                .add("availability", availability)
                .toString();
    }

    @Override
    protected Person clone() {
        return new TeachingStaff(name, phone, email, username, position, new HashSet<>(tags), availability);
    }

    /**
     * Creates a temporarily mutable copy of this TeachingStaff, allowing modification
     * through a delegate function. This is useful for operations that
     * require temporary mutability (e.g., editing) before finalizing the object.
     *
     * @param delegate A consumer that receives the mutable copy and can modify it
     * @return An immutable TeachingStaff instance that has been modified by the delegate.
     * @throws NullPointerException if the delegate is null.
     */
    public TeachingStaff cloneIntoTeachingStaff(Consumer<MutableTeachingStaff> delegate) {
        var clonedPerson = new MutableTeachingStaff((TeachingStaff) clone());
        return (TeachingStaff) cloneIntoInner(delegate, clonedPerson);
    }

    /**
     * A temporarily mutable version of TeachingStaff, allowing modification of its fields.
     * Allows clean editing of an object without violating the functional
     * immutability requirements of TeachingStaff
     */
    public static final class MutableTeachingStaff extends MutablePerson {
        MutableTeachingStaff(TeachingStaff person) {
            super(person);
        }

        public void setPosition(Position position) {
            checkEditable();
            requireNonNull(position);
            var p = (TeachingStaff) person;
            p.position = position;
        }
    }

}
