@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class TeachingStaff
Class Email
Class Name
Class Phone
Class Username
Class Position
Class TimeSlot
Class "{abstract}\nAbstractTag" as AbstractTag
Class Tag
Class RestrictedTag

Class "{abstract}\nTagSchema" as TagSchema
Class "{abstract}\nRegexTagSchema" as RegexTagSchema
Class LabTagSchema
Class TutorialTagSchema
Class CourseTagSchema

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Username
Person o--> "*" AbstractTag

TeachingStaff -up-|> Person
TeachingStaff *--> Position
TeachingStaff *--> "*" TimeSlot

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> Username

Tag .up.|> AbstractTag
RestrictedTag .up.|> AbstractTag
RestrictedTag *--> "1" TagSchema
RegexTagSchema -up-|> TagSchema
LabTagSchema .up.|> RegexTagSchema
TutorialTagSchema .up.|> RegexTagSchema
CourseTagSchema .up.|> RegexTagSchema

ModelManager --> "~* filtered" Person
@enduml
